// Location data for SEO pages

export interface LocationData {
  slug: string;
  name: string;
  description: string;
}

export const countries: LocationData[] = [
  { slug: "united-states", name: "United States", description: "Connect with strangers across America for random video chats" },
  { slug: "united-kingdom", name: "United Kingdom", description: "Meet new people from the UK through live video conversations" },
  { slug: "canada", name: "Canada", description: "Chat with friendly Canadians via random video calls" },
  { slug: "australia", name: "Australia", description: "Connect with Aussies for exciting video chat experiences" },
  { slug: "india", name: "India", description: "Meet diverse people from India through video chat" },
  { slug: "germany", name: "Germany", description: "Talk with Germans and practice language through video" },
  { slug: "france", name: "France", description: "Connect with French speakers for cultural exchange" },
  { slug: "spain", name: "Spain", description: "Meet Spanish-speaking friends through video chat" },
  { slug: "italy", name: "Italy", description: "Chat with Italians and explore Italian culture" },
  { slug: "brazil", name: "Brazil", description: "Connect with vibrant Brazilian community via video" },
  { slug: "mexico", name: "Mexico", description: "Meet friendly Mexicans through random video chats" },
  { slug: "russia", name: "Russia", description: "Talk with people from Russia in video conversations" },
  { slug: "japan", name: "Japan", description: "Connect with Japanese culture through video chat" },
  { slug: "south-korea", name: "South Korea", description: "Meet Korean friends via live video calls" },
  { slug: "china", name: "China", description: "Chat with people from China through video" },
  { slug: "indonesia", name: "Indonesia", description: "Connect with Indonesians for cultural exchange" },
  { slug: "philippines", name: "Philippines", description: "Meet friendly Filipinos through video chat" },
  { slug: "pakistan", name: "Pakistan", description: "Talk with people from Pakistan via video" },
  { slug: "bangladesh", name: "Bangladesh", description: "Connect with Bangladeshi community through video" },
  { slug: "nigeria", name: "Nigeria", description: "Meet vibrant Nigerian community via video chat" },
  { slug: "egypt", name: "Egypt", description: "Chat with Egyptians and learn about their culture" },
  { slug: "south-africa", name: "South Africa", description: "Connect with South Africans through video calls" },
  { slug: "turkey", name: "Turkey", description: "Meet Turkish friends via random video chat" },
  { slug: "poland", name: "Poland", description: "Talk with Polish people through video conversations" },
  { slug: "ukraine", name: "Ukraine", description: "Connect with Ukrainians for cultural exchange" },
  { slug: "netherlands", name: "Netherlands", description: "Meet Dutch speakers through video chat" },
  { slug: "belgium", name: "Belgium", description: "Chat with Belgians via live video calls" },
  { slug: "sweden", name: "Sweden", description: "Connect with Swedish community through video" },
  { slug: "norway", name: "Norway", description: "Meet Norwegians for video chat experiences" },
  { slug: "denmark", name: "Denmark", description: "Talk with Danish people via video chat" },
  { slug: "finland", name: "Finland", description: "Connect with Finns through random video calls" },
  { slug: "switzerland", name: "Switzerland", description: "Meet Swiss people for cultural exchange" },
  { slug: "austria", name: "Austria", description: "Chat with Austrians via video conversations" },
  { slug: "portugal", name: "Portugal", description: "Connect with Portuguese speakers through video" },
  { slug: "greece", name: "Greece", description: "Meet Greeks and explore their culture via video" },
  { slug: "czech-republic", name: "Czech Republic", description: "Talk with Czech people through video chat" },
  { slug: "romania", name: "Romania", description: "Connect with Romanians for video conversations" },
  { slug: "hungary", name: "Hungary", description: "Meet Hungarian friends via video chat" },
  { slug: "argentina", name: "Argentina", description: "Chat with Argentinians through live video" },
  { slug: "chile", name: "Chile", description: "Connect with Chilean community via video" },
  { slug: "colombia", name: "Colombia", description: "Meet Colombians for exciting video chats" },
  { slug: "peru", name: "Peru", description: "Talk with Peruvians through video conversations" },
  { slug: "venezuela", name: "Venezuela", description: "Connect with Venezuelans via video chat" },
  { slug: "thailand", name: "Thailand", description: "Meet Thai people for cultural exchange" },
  { slug: "vietnam", name: "Vietnam", description: "Chat with Vietnamese community through video" },
  { slug: "malaysia", name: "Malaysia", description: "Connect with Malaysians via video calls" },
  { slug: "singapore", name: "Singapore", description: "Meet Singaporeans for video chat experiences" },
  { slug: "new-zealand", name: "New Zealand", description: "Talk with Kiwis through random video chat" },
  { slug: "ireland", name: "Ireland", description: "Connect with Irish people via video conversations" },
  { slug: "israel", name: "Israel", description: "Meet people from Israel through video chat" }
];

export const cities: LocationData[] = [
  { slug: "new-york", name: "New York", description: "Chat with strangers from the Big Apple" },
  { slug: "los-angeles", name: "Los Angeles", description: "Connect with people from the City of Angels" },
  { slug: "chicago", name: "Chicago", description: "Meet Chicagoans through video chat" },
  { slug: "london", name: "London", description: "Talk with Londoners via random video calls" },
  { slug: "paris", name: "Paris", description: "Connect with Parisians for cultural exchange" },
  { slug: "tokyo", name: "Tokyo", description: "Meet people from Tokyo through video chat" },
  { slug: "sydney", name: "Sydney", description: "Chat with Sydneysiders via live video" },
  { slug: "toronto", name: "Toronto", description: "Connect with diverse Toronto community" },
  { slug: "mumbai", name: "Mumbai", description: "Meet people from Mumbai through video" },
  { slug: "delhi", name: "Delhi", description: "Chat with Delhi residents via video calls" },
  { slug: "berlin", name: "Berlin", description: "Connect with Berliners for video conversations" },
  { slug: "madrid", name: "Madrid", description: "Meet people from Madrid through video chat" },
  { slug: "rome", name: "Rome", description: "Talk with Romans via random video calls" },
  { slug: "barcelona", name: "Barcelona", description: "Connect with Barcelona locals through video" },
  { slug: "amsterdam", name: "Amsterdam", description: "Chat with Amsterdam residents via video" },
  { slug: "dubai", name: "Dubai", description: "Meet people from Dubai for video chat" },
  { slug: "singapore-city", name: "Singapore", description: "Connect with Singaporeans through video" },
  { slug: "hong-kong", name: "Hong Kong", description: "Talk with Hong Kongers via video calls" },
  { slug: "shanghai", name: "Shanghai", description: "Meet people from Shanghai through video" },
  { slug: "beijing", name: "Beijing", description: "Chat with Beijing residents via video" },
  { slug: "seoul", name: "Seoul", description: "Connect with Seoul locals through video chat" },
  { slug: "bangkok", name: "Bangkok", description: "Meet people from Bangkok via video calls" },
  { slug: "istanbul", name: "Istanbul", description: "Talk with Istanbul residents through video" },
  { slug: "moscow", name: "Moscow", description: "Connect with Muscovites for video chat" },
  { slug: "sao-paulo", name: "São Paulo", description: "Meet people from São Paulo via video" },
  { slug: "mexico-city", name: "Mexico City", description: "Chat with Mexico City locals through video" },
  { slug: "miami", name: "Miami", description: "Connect with Miami residents for video calls" },
  { slug: "las-vegas", name: "Las Vegas", description: "Meet people from Vegas via video chat" },
  { slug: "san-francisco", name: "San Francisco", description: "Talk with San Franciscans through video" },
  { slug: "houston", name: "Houston", description: "Connect with Houston community via video" },
  { slug: "boston", name: "Boston", description: "Chat with Bostonians through video calls" },
  { slug: "seattle", name: "Seattle", description: "Meet Seattle residents via video chat" },
  { slug: "atlanta", name: "Atlanta", description: "Connect with Atlanta locals through video" },
  { slug: "denver", name: "Denver", description: "Talk with Denver residents via video calls" },
  { slug: "phoenix", name: "Phoenix", description: "Meet people from Phoenix through video" },
  { slug: "philadelphia", name: "Philadelphia", description: "Chat with Philly residents via video" },
  { slug: "manchester", name: "Manchester", description: "Connect with Manchester locals through video" },
  { slug: "birmingham", name: "Birmingham", description: "Meet Birmingham residents via video chat" },
  { slug: "glasgow", name: "Glasgow", description: "Talk with Glasgow locals through video calls" },
  { slug: "dublin", name: "Dublin", description: "Connect with Dubliners for video conversations" },
  { slug: "melbourne", name: "Melbourne", description: "Chat with Melbourne residents via video" },
  { slug: "brisbane", name: "Brisbane", description: "Meet people from Brisbane through video" },
  { slug: "auckland", name: "Auckland", description: "Connect with Auckland locals via video chat" },
  { slug: "vancouver", name: "Vancouver", description: "Talk with Vancouver residents through video" },
  { slug: "montreal", name: "Montreal", description: "Meet Montrealers for video conversations" },
  { slug: "tel-aviv", name: "Tel Aviv", description: "Chat with Tel Aviv residents via video" },
  { slug: "lisbon", name: "Lisbon", description: "Connect with Lisbon locals through video chat" },
  { slug: "vienna", name: "Vienna", description: "Meet people from Vienna via video calls" },
  { slug: "brussels", name: "Brussels", description: "Talk with Brussels residents through video" },
  { slug: "zurich", name: "Zurich", description: "Connect with Zurich locals for video chat" }
];

export const areas: LocationData[] = [
  { slug: "california", name: "California", description: "Connect with Californians across the Golden State" },
  { slug: "texas", name: "Texas", description: "Meet people from the Lone Star State" },
  { slug: "florida", name: "Florida", description: "Chat with Floridians via video calls" },
  { slug: "new-york-state", name: "New York State", description: "Connect with New Yorkers through video" },
  { slug: "england", name: "England", description: "Meet people from England via video chat" },
  { slug: "scotland", name: "Scotland", description: "Talk with Scots through video conversations" },
  { slug: "wales", name: "Wales", description: "Connect with Welsh people via video chat" },
  { slug: "northern-ireland", name: "Northern Ireland", description: "Chat with people from Northern Ireland" },
  { slug: "bavaria", name: "Bavaria", description: "Meet Bavarians through video calls" },
  { slug: "catalonia", name: "Catalonia", description: "Connect with Catalans for video chat" },
  { slug: "lombardy", name: "Lombardy", description: "Talk with people from Lombardy via video" },
  { slug: "ile-de-france", name: "Île-de-France", description: "Meet people from Paris region" },
  { slug: "ontario", name: "Ontario", description: "Connect with Ontarians through video chat" },
  { slug: "quebec", name: "Quebec", description: "Chat with Quebecers via video calls" },
  { slug: "new-south-wales", name: "New South Wales", description: "Meet people from NSW through video" },
  { slug: "victoria-australia", name: "Victoria", description: "Connect with Victorians via video chat" },
  { slug: "maharashtra", name: "Maharashtra", description: "Talk with people from Maharashtra" },
  { slug: "uttar-pradesh", name: "Uttar Pradesh", description: "Meet people from UP through video" },
  { slug: "bengal", name: "West Bengal", description: "Connect with Bengalis via video chat" },
  { slug: "tamil-nadu", name: "Tamil Nadu", description: "Chat with Tamil Nadu residents" },
  { slug: "karnataka", name: "Karnataka", description: "Meet people from Karnataka through video" },
  { slug: "punjab", name: "Punjab", description: "Connect with Punjabis for video conversations" },
  { slug: "midwest", name: "Midwest USA", description: "Chat with people from America's Heartland" },
  { slug: "southeast-usa", name: "Southeast USA", description: "Meet people from the American Southeast" },
  { slug: "northeast-usa", name: "Northeast USA", description: "Connect with Northeasterners via video" },
  { slug: "southwest-usa", name: "Southwest USA", description: "Talk with Southwestern residents through video" },
  { slug: "pacific-northwest", name: "Pacific Northwest", description: "Meet people from the PNW via video chat" },
  { slug: "south-england", name: "South England", description: "Connect with South England locals" },
  { slug: "north-england", name: "North England", description: "Chat with North England residents" },
  { slug: "central-london", name: "Central London", description: "Meet people from Central London" },
  { slug: "greater-manchester", name: "Greater Manchester", description: "Connect with Greater Manchester area" },
  { slug: "west-midlands", name: "West Midlands", description: "Talk with West Midlands residents" },
  { slug: "greater-sydney", name: "Greater Sydney", description: "Meet people from Sydney metro area" },
  { slug: "greater-melbourne", name: "Greater Melbourne", description: "Connect with Melbourne metro residents" },
  { slug: "greater-toronto", name: "Greater Toronto", description: "Chat with GTA residents via video" },
  { slug: "san-francisco-bay", name: "San Francisco Bay Area", description: "Meet Bay Area locals through video" },
  { slug: "southern-california", name: "Southern California", description: "Connect with SoCal residents" },
  { slug: "northern-california", name: "Northern California", description: "Talk with NorCal people via video" },
  { slug: "greater-los-angeles", name: "Greater Los Angeles", description: "Meet LA metro area residents" },
  { slug: "chicagoland", name: "Chicagoland", description: "Connect with Chicago metro area" },
  { slug: "dallas-fort-worth", name: "Dallas-Fort Worth", description: "Chat with DFW metroplex residents" },
  { slug: "greater-houston", name: "Greater Houston", description: "Meet Houston metro area locals" },
  { slug: "greater-miami", name: "Greater Miami", description: "Connect with Miami metro residents" },
  { slug: "greater-atlanta", name: "Greater Atlanta", description: "Talk with Atlanta metro area people" },
  { slug: "greater-boston", name: "Greater Boston", description: "Meet Boston metro area residents" },
  { slug: "greater-seattle", name: "Greater Seattle", description: "Connect with Seattle metro locals" },
  { slug: "greater-phoenix", name: "Greater Phoenix", description: "Chat with Phoenix metro residents" },
  { slug: "greater-philadelphia", name: "Greater Philadelphia", description: "Meet Philly metro area people" },
  { slug: "greater-paris", name: "Greater Paris", description: "Connect with Paris metro region" },
  { slug: "greater-tokyo", name: "Greater Tokyo", description: "Talk with Tokyo metro area residents" }
];

export function getLocationBySlug(slug: string, type: 'country' | 'city' | 'area'): LocationData | undefined {
  const locations = type === 'country' ? countries : type === 'city' ? cities : areas;
  return locations.find(loc => loc.slug === slug);
}
